disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - function_body_length
  - syntactic_sugar
  - force_cast
  - file_length
  - line_length
  - type_name
  - nesting
  - type_body_length
included:
  - Package.swift
  - Sources
  - Tests
